---

- name: ensure required packages are present
  apt: name={{ item }} state=present
  with_items:
    - build-essential
    - libffi-dev
    - libssl-dev
    - python-dev
    - python-usb

- name: ensure git repo is present
  git: repo={{ repo_url }} version={{ repo_branch }} dest={{ repo_dest }}
