---

- name: ensure required packages are present
  apt: name={{ item }} state=present
  with_items:
    - git
    - python-pip
    - vim

- name: ensure git repo is present
  git: repo={{ repo_url }} version={{ repo_branch }} dest={{ repo_dest }}
